### ISSUE TITLE
How can i show an icon inside circleProps

### ISSUE THREAD

**Issue by nidhinkumar06** [jpb12/react-tree-graph#51] opened 2019-04-29 11:06 UTC
Is it possible to add icon inside circleProps. I have tried with mask like below
`<mask id="myMask" maskContentUnits="objectBoundingBox">
          <rect fill="white" x="0" y="0" width="100%" height="100%" />
          <polygon fill="black" points="0.5,0.2 0.68,0.74 0.21,0.41 0.79,0.41 0.32,0.74" />
        </mask>`
`
<Tree
        data={data}
    	  height={400}
    	  width={400}
        svgProps={{
    			className: 'custom'
    		}}
        nodeRadius={10}
        circleProps={{ fill: 'red', mask: 'url(#myMask)' }}
        animated>
`

But if we need to pass dynamic icons or images how can we do it

**Comment by jpb12** [comment] 2019-04-29 20:31
Duplicate of #32. Define an image inside `<defs>`.

**Closed by jpb12** 2019-04-29 20:31 UTC
Labels: duplicate

**Comment by nidhinkumar06** [comment] 2019-04-30 10:28
I found the answer for it
`<defs>
          <pattern id="image1" x="0" y="0" patternContentUnits="objectBoundingBox" height="100%" width="100%">
            <image
              height="1"
              weight="1"
              preserveAspectRatio="none"
              href='https://cdn.pixabay.com/photo/2013/07/12/17/41/computer-mouse-152249_960_720.png'>
              </image>
          </pattern>
        </defs>`
