### ISSUE TITLE
can add drag and drop the nodes?

### ISSUE THREAD

**Issue by romanown** [jpb12/react-tree-graph#75] opened 2020-10-04 22:59 UTC

**Comment by jpb12** [comment] 2020-10-05 10:00
Duplicate of #40.

There's no built in logic for drag and drop but it can be configured by setting up the events yourself.

**Closed by jpb12** 2020-10-05 10:00 UTC
Labels: question

**Comment by romanown** [comment] 2020-10-05 11:10
it is very userfull option extends it. i can not do it. may be You have any tryed for this? help me please. sanks for any help.
