### ISSUE TITLE
change node icon and open menu on click

### ISSUE THREAD

**Issue by vitaly87** [jpb12/react-tree-graph#63] opened 2019-12-22 08:46 UTC
Is it possible to add popup menu on node when right click on node?
Also how can change node icon need some svg?
and the last one is it possible to have straight lines ?

**Comment by jpb12** [comment] 2019-12-22 12:13
The first is a duplicate of #62.
The second is a duplicate of #32.
The third is not currently possible.

**Comment by jpb12** [comment] 2020-03-16 11:46
This is now possible in 4.1.0. I've added an [example](https://jpb12.github.io/react-tree-graph/#customPath) to the docs.

**Closed by jpb12** 2020-03-16 11:46 UTC
Labels: enhancement
